Add logic skeleton
AY2122S2-CS2103T-T09-4/tp pull request #29
Opened 2022-03-06 12:02 UTC by redpelican2108

2022-03-06 12:18 UTC, mazx4960 reviewed
I think should be merged into skeleton branch instead

2022-03-06 12:18 UTC, mazx4960 commented on src/main/java/seedu/address/logic/LogicManager.java
> +        return model.getFilteredIBook();
Should this be getFilteredProductList instead

2022-03-06 12:18 UTC, mazx4960 commented on src/main/java/seedu/address/logic/Logic.java
> +    ObservableList<Product> getFilteredIBook();
should this be getFilteredProductList instead

2022-03-06 12:18 UTC, mazx4960 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> -package seedu.address.logic.commands;
Is there a reason for deleting this command?

2022-03-06 12:18 UTC, mazx4960 commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> -package seedu.address.logic.parser;
Is there a reason for deleting this command

2022-03-06 16:58 UTC, redpelican2108 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> -package seedu.address.logic.commands;
just to clear the clutter, but we can keep it if we want

2022-03-06 17:00 UTC, redpelican2108 commented
Changed it to skeletal

2022-03-06 17:01 UTC, redpelican2108 commented on src/main/java/seedu/address/logic/LogicManager.java
> +        return model.getFilteredIBook();
The part in model hasn't been changed so it depends on that part

2022-03-07 10:01 UTC, MechFroG88 requested changes
Reason for CI build failure

2022-03-07 10:01 UTC, MechFroG88 commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_DESCRIPTION + "Very Tasty"
Syntax error here
```suggestion
            + PREFIX_DESCRIPTION + "Very Tasty";
```

2022-03-07 10:04 UTC, MechFroG88 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> -package seedu.address.logic.commands;
We are implementing the edit command in v1.2 rite? I think it might be necessary to keep

2022-03-07 11:43 UTC, DavidTan0527 commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
>   * Deletes a person identified using it's displayed index from the address book.
`person` should be changed to `product`

2022-03-07 12:34 UTC, redpelican2108 commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_DESCRIPTION + "Very Tasty"
Fixed

2022-03-08 03:19 UTC, merged